import { writeFile } from "node:fs/promises";
import { createThemeCss } from "@tanstack/highlight/theme";
import { githubDarkTheme } from "@tanstack/highlight/themes/github-dark";
import { githubLightTheme } from "@tanstack/highlight/themes/github-light";

/**
 * Both code surfaces: the `pre` a markdown fence renders as, and the one a
 * whole code file is drawn in. They are two components and one appearance, so
 * the theme's base rules have to name both.
 */
const CODE_BLOCK_SELECTOR = "pre.tm-code, pre.th-code";

const OUTPUT = new URL("../src/styles/highlight.css", import.meta.url);

/**
 * Writes the syntax theme out as plain CSS.
 *
 * The highlighter emits class names and takes its colours from custom
 * properties, so a theme is a stylesheet rather than a runtime concern — which
 * is why this is generated once and committed instead of being built on every
 * render. The dark half hangs off `.dark`, the class the theme switcher already
 * puts on the document.
 */
const generate = async () => {
  const css = createThemeCss({
    codeBlockSelector: CODE_BLOCK_SELECTOR,
    dark: githubDarkTheme,
    darkSelector: ".dark",
    light: githubLightTheme,
    // Only the file viewer numbers its lines; a fence inside a message never
    // does, so this stays one selector — the library appends to it and a
    // comma-separated list would only apply to the last item.
    lineNumbersSelector: "pre.th-code--line-numbers",
  });

  await writeFile(
    OUTPUT,
    `/* Generated by scripts/highlight-theme.ts. Run \`bun run theme:highlight\` to refresh. */\n${css}\n`
  );
};

await generate();
