#!/usr/bin/env bun

/**
 * Puts our one index back on the auth library's `member` table.
 *
 * The library indexes `organization_id` and `user_id` separately and declares
 * no composite unique, so the same user can hold two membership rows in the
 * same workspace with different roles — and every authorization query would
 * then be reading whichever row came back first. It is our database even where
 * the table is theirs, so the index belongs there.
 *
 * It cannot simply be typed into the schema file: that file is generated, and a
 * hand-edit disappears the next time the generator runs. Nor can it live in a
 * module of ours, because drizzle attaches an index to the table declaration it
 * is written in, and the migration tool builds its snapshot from those
 * declarations — an index declared anywhere else would show up as a drop on the
 * next diff. So the generator is followed by this, and the pair of them is what
 * `auth:generate` means. `schema/auth.test.ts` is the check that it ran.
 *
 * Loud on anything unexpected: a generator whose output no longer matches the
 * anchors below has probably changed the table too, and silently writing no
 * index would leave the duplicate-membership hole open with nothing to say so.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const SCHEMA_PATH = fileURLToPath(
  new URL("../src/schema/auth.ts", import.meta.url)
);

/** The index name, which is also how a second run recognizes its own work. */
const INDEX_NAME = "member_org_user_uq";

/**
 * Stamped at the top of the generated file, because the one thing that makes a
 * generated file dangerous is a reader who cannot tell.
 */
const BANNER = `/**
 * Generated by the auth library's schema generator. Do not edit by hand — run
 * \`bun run auth:generate\` in this package instead, which regenerates this file
 * and re-applies the one index of ours that lives here.
 *
 * These tables are the library's, but the database is ours: drizzle-kit owns
 * every migration in this repo, so the auth tables ship in the same chain as
 * every other table rather than through a second migrator.
 */
`;

/** The last of the library's own `member` indexes; ours goes after it. */
const ANCHOR =
  /index\(\s*"member_userId_idx"\s*\)\s*\.on\(\s*table\.userId\s*\)/;

/** Whitespace is the formatter's business; this only has to parse. */
const INDEX = `uniqueIndex("${INDEX_NAME}").on(table.organizationId, table.userId)`;

const fail = (reason: string) => {
  process.stderr.write(`auth-schema-index: ${reason}\n`);
  process.exit(1);
};

const source = await readFile(SCHEMA_PATH, "utf8");

const banner = source.startsWith("/**") ? "" : BANNER;

if (source.includes(INDEX_NAME)) {
  if (banner !== "") {
    await writeFile(SCHEMA_PATH, banner + source);
  }
  process.stdout.write(`auth-schema-index: ${INDEX_NAME} already declared\n`);
  process.exit(0);
}

if (!ANCHOR.test(source)) {
  fail(
    "the generated schema no longer declares member_userId_idx — check what the generator emits for `member` before trusting this file"
  );
}

if (!source.includes("uniqueIndex")) {
  fail("the generated schema no longer imports uniqueIndex");
}

await writeFile(
  SCHEMA_PATH,
  banner + source.replace(ANCHOR, (matched) => `${matched},\n${INDEX}`)
);

process.stdout.write(`auth-schema-index: added ${INDEX_NAME} to member\n`);
